language: go

go:
  - 1.15.x
  - tip

notifications:
  email: false

services:
  - docker


install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.35.2
scripts:
- book/scripts/lint.sh
- server/scripts/lint.sh
install:
- docker pull postgres:9.6.20
- docker pull mongo:4.4.3
script:
- docker-compose up -d
scripts:
- book/scripts/test.sh
scripts:
- server/scripts/test.sh

after_failure:
  - git rebase -i HEAD^^
