version: "3.9"

services:
  mongo:
    restart: on-failure
    image: mongo:4.4.3
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=qwerty

  postgres:
    restart: on-failure
    image: postgres:9.6.20
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=qwerty
