version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.15.7-buster
      - image: circleci/mongo:4.4.3
        environment:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: qwerty
      - image: circleci/postgres:9.6.20
        environment:
          POSTGRES_PASSWORD: qwerty
    working_directory: /go/src/github.com/ivyoverflow/pub-sub
    steps:
      - checkout
      - run: cd book/ && go test -covermode=atomic ./...
      - run: cd server/ && go test -covermode=atomic ./...
workflows:
  version: 2
  build-workflow:
    jobs:
      - build
