version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.15.7-buster
      - image: circleci/mongo:4.4.3
        environment:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: qwerty
      - image: circleci/postgres:9.6.20
        environment:
          POSTGRES_PASSWORD: qwerty
      - image: circleci/redis:rc-alpine3.13
    working_directory: /go/src/github.com/ivyoverflow/pub-sub
    steps:
      - checkout
      - run:
          name: "Migrate installation"
          command: |
            go get -tags 'postgres' -u github.com/golang-migrate/migrate/cmd/migrate
      - run:
          name: "Init PostgreSQL migrations"
          command: |
            migrate -path ./api/internal/storage/postgres/migrations -database postgres://postgres:qwerty@localhost:5432/postgres?sslmode=disable up
      - run:
          name: "GolangCI installation"
          command: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.35.2
      - run:
          name: "Run GolangCI"
          command: |
            cd api/ && golangci-lint run -v --timeout 2m
            cd ../notifier/ && golangci-lint run -v --timeout 2m
      - run:
          name: "Run unit tests"
          command: |
            cd api/ && go test -covermode=atomic ./...
            cd ../notifier/ && go test -covermode=atomic ./...
workflows:
  version: 2
  build-workflow:
    jobs:
      - build
