export PGHOST="localhost"
export PGPORT="5432"
export PGUSER="postgres"
export PGNAME="postgres"
export PGPASSWORD="qwerty"
export PGMIGRATIONSPATH="file://internal/repository/postgres/migrations"
export PGSSLMODE="disable"

export ADDR="localhost"
export PORT="8080"

export MONGOUSER="mongo"
export MONGOPASSWORD="qwerty"
export MONGOHOST="localhost"
export MONGOPORT="27017"
export MONGONAME="bookdb"
