// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	redis "github.com/go-redis/redis/v8"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockNotifierRepository is a mock of Notifier interface
type MockNotifierRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNotifierRepositoryMockRecorder
}

// MockNotifierRepositoryMockRecorder is the mock recorder for MockNotifierRepository
type MockNotifierRepositoryMockRecorder struct {
	mock *MockNotifierRepository
}

// NewMockNotifierRepository creates a new mock instance
func NewMockNotifierRepository(ctrl *gomock.Controller) *MockNotifierRepository {
	mock := &MockNotifierRepository{ctrl: ctrl}
	mock.recorder = &MockNotifierRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockNotifierRepository) EXPECT() *MockNotifierRepositoryMockRecorder {
	return m.recorder
}

// Publish mocks base method
func (m *MockNotifierRepository) Publish(ctx context.Context, book string, message interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, book, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish
func (mr *MockNotifierRepositoryMockRecorder) Publish(ctx, book, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockNotifierRepository)(nil).Publish), ctx, book, message)
}

// Subscribe mocks base method
func (m *MockNotifierRepository) Subscribe(ctx context.Context, book string) <-chan *redis.Message {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", ctx, book)
	ret0, _ := ret[0].(<-chan *redis.Message)
	return ret0
}

// Subscribe indicates an expected call of Subscribe
func (mr *MockNotifierRepositoryMockRecorder) Subscribe(ctx, book interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockNotifierRepository)(nil).Subscribe), ctx, book)
}
